/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProDepositAbi } from "./ProDepositAbi";
export * as factories from "./factories";
export { ProDepositAbi__factory } from "./factories/ProDepositAbi__factory";
